export class Condition {
  cust:string;
  goodn:string;
  fromDt:string;
  toDt:string;
  entDate:string;
  ent1:string;
  ent2:string;
  blno:string;
  ctno:string;
  reqDt:string;
  lotno1:string;
  org:string;
  SEND:string;
  SEND2:string;
  keyG:string;
  PLATENO:string;
  RMK:string;
  CUSTNM:string;
}
